error_dict = \
    {
        [
            {"080A000E": "Trace message script.manager"},
            {"080A000F": "Trace message script.python"},
            {"080A0042": "Scheduler message"},
            {"080A00A0": "Converting the Scheduler program"},
            {"080A0100": "Error cleared"},
            {"080A0101": "Command 'Errors cleared' executed"},
            {"080A0102": "No pending errors and warnings"},
            {"080A0103": "Command 'Reset all pending diagnostics' executed"},
            {"080A0110": "Trace message common.log.diagnosis"},
            {"080A0112": "Trace message common.log.trace"},
            {"080A0300": "Security: Change in user management"},
            {"080A0301": "Security: Change in certificate management"},
            {"080A0302": "Security: Change in firewall configuration"},
            {"080A0303": "Security: Change in vpn configuration"},
            {"080A0304": "Security: Change to remote logging administration"},
            {"080A0400": "Loading configuration started"},
            {"080A0401": "Loading configuration successfully finished"},
            {"080A0402": "Saving configuration started"},
            {"080A0403": "Saving configuration successfully finished"},
            {"080A0410": "Trace message"},
            {"080A0420": "Creating setup"},
            {"080A0421": "Setup created"},
            {"080A0422": "Setup started"},
            {"080A0423": "Setup finished"},
            {"080A0450": "Archive successfully created"},
            {"080A0451": "Archive successfully restored"},
            {"080A0500": "Change in network management"},
            {"080A0510": "PackageManager information"},
            {"080A0520": "Storage management information"},
            {"080A0530": "System management change"},
            {"080A0600": "Trace message comm.datalayer"},
            {"080A0601": "Trace message comm.datalayer.framework"},
            {"080A0602": "Trace message web.automation"},
            {"080A0603": "Trace message common.systemhandler"},
            {"080A0604": "Trace message app.automationframework"},
            {"080A0650": "Application 'Automation Core' event"},
            {"080A0FFF": "Trace message common.scheduler"},
            {"080E000E": "Trace warning script.manager"},
            {"080E000F": "Trace warning script.python"},
            {"080E0017": "Hardware watchdog warning"},
            {"080E0023": "Utilization in the critical section 'WARNING'"},
            {"080E00A0": "Converting the Scheduler program"},
            {"080E0110": "Trace warning common.log.diagnosis"},
            {"080E0112": "Trace warning common.log.trace"},
            {"080E0200": "HTTP client error"},
            {"080E0300": "Security: User management warning"},
            {"080E0301": "Security: Certificate management warning"},
            {"080E0303": "Security: Warning in the VPN configuration"},
            {"080E0304": "Security: Warning in remote logging administration"},
            {"080E0305": "Bootloader unlocked!"},
            {"080E0410": "Trace warning"},
            {"080E0500": "Warning in network management"},
            {"080E0510": "PackageManager warning"},
            {"080E0520": "Storage management warning"},
            {"080E0530": "System management warning"},
            {"080E0540": "Warning detected during health monitoring"},
            {"080E0550": "License manager warning"},
            {"080E05FF": "Device Administration: Warning"},
            {"080E0600": "Trace warning comm.datalayer"},
            {"080E0601": "Trace warning comm.datalayer.framework"},
            {"080E0602": "Trace warning web.automation"},
            {"080E0603": "Trace warning common.systemhandler"},
            {"080E0604": "Trace warning app.automationframework"},
            {"080E0FFF": "Trace warning common.scheduler"},
            {"080F0000": "Error in process handling for script instance"},
            {"080F0001": "Error during backup or restoration of script manager"},
            {"080F000E": "Trace error script.manager"},
            {"080F000F": "Trace error script.python"},
            {"080F0017": "Task watchdog error"},
            {"080F0023": "Error on configuration"},
            {"080F0042": "Error in Scheduler system"},
            {"080F0066": "Error when restoring the configuration"},
            {"080F0088": "Error during automatic reallocation of the callables"},
            {"080F00A0": "Failed to create a callable"},
            {"080F00B0": "Condition detected that triggered the safe mode"},
            {"080F0100": "Error in diagnostic system"},
            {"080F0110": "Trace error common.log.diagnosis"},
            {"080F0112": "Trace error common.log.trace"},
            {"080F0200": "HTTP server error"},
            {"080F0300": "Security: Error in certificate management"},
            {"080F0301": "Security: Error in the user management"},
            {"080F0303": "Security: Error in the VPN configuration"},
            {"080F0304": "Security: Error in remote logging administration"},
            {"080F0400": "Loading configuration failed"},
            {"080F0402": "Saving configuration failed"},
            {"080F0410": "Trace error"},
            {"080F0420": "Creating setup failed"},
            {"080F0422": "Setup failed"},
            {"080F0450": "Backup failed"},
            {"080F0451": "Restore operation failed"},
            {"080F0452": "Restore operation failed completely"},
            {"080F0500": "Error in network management"},
            {"080F0510": "PackageManager error"},
            {"080F0511": "System management error"},
            {"080F0520": "Storage management error"},
            {"080F0521": "Memory task processing failed"},
            {"080F0530": "System management error"},
            {"080F0531": "Error during image upload process"},
            {"080F0532": "Factory reset cannot be executed"},
            {"080F0533": "Factory reset preparation failed"},
            {"080F0540": "Failure detected during health monitoring"},
            {"080F0550": "Error in license management"},
            {"080F0560": "Error in device discovery"},
            {"080F0600": "Trace error comm.datalayer"},
            {"080F0601": "Trace error comm.datalayer.framework"},
            {"080F0602": "Trace error web.automation"},
            {"080F0603": "Trace error common.systemhandler"},
            {"080F0604": "Trace error app.automationframework"},
            {"080F0650": "Application 'Automation Core' error"},
            {"080F0E00": "Loading configuration not possible in current state"},
            {"080F0FFF": "Trace error common.scheduler"},
            {"080F2000": "Error while running script"},
            {"080F2001": "Error in task/requ. comm. between script manager/instance"},
            {"080F2002": "Error in Data Layer of script manager"},
            {"080F2003": "Error in system configuration"},
            {"080F6017": "Task watchdog error"},
            {"080F6019": "Utilization in the critical section 'FATAL'"},
            {"080F6023": "Utilization in the critical section 'ERROR'"},
            {"080F6042": "Error in Scheduler system"},
            {"080F60A0": "Error in the equidistance of the Scheduler"},
            {"080F60B0": "Condition detected that triggered a safe machine state"},
            {"080F6550": "Critical error in license management"},
            {"080F8017": "Hardware watchdog error"},
            {"080F8042": "Error in Scheduler system"},
            {"080F80B0": "Exception occurred"},
            {"080F9540": "Critical failure detected during health monitoring"},
            {"080F9550": "Fatal error in license management"},
            {"090A0000": "Commanded dynamic parameters exceed axis limits"},
            {"090A0001": "Commanded dynamic parameters exceed kinematic limits"},
            {"090A0002": "Configuration modified booting"},
            {"090A0003": "Motion object error level set by application"},
            {"090A0004": "Waiting for motion license"},
            {"090A0010": "Message in the jog command of the axis"},
            {"090A0011": "Message in the jog command of the kinematics"},
            {"090A0012": "Message in the axis configuration"},
            {"090A0013": "Message in the kinematic configuration"},
            {"090A0201": "AxisProfile booting message"},
            {"090A02FF": "Trace message common.axisprofile"},
            {"090A04FF": "Trace message plc.cmp.motion"},
            {"090A0500": "Axis limits exceeded"},
            {"090A0501": "Command message for the synchronized position motion"},
            {"090A0FFD": "Trace message motion.script"},
            {"090A0FFE": "Trace message motion.collisionavoidance"},
            {"090A0FFF": "Trace message motion.core"},
            {"090E0000": "Commanded dynamic parameters exceed axis limits"},
            {"090E0001": "Commanded dynamic parameters exceed kinematic limits"},
            {"090E0002": "Gantry configuration inconsistent"},
            {"090E0010": "Warning in jog command of the axis"},
            {"090E0011": "Warning in the jog command of the kinematics"},
            {"090E0201": "AxisProfile booting warning"},
            {"090E02FF": "Trace warning common.axisprofile"},
            {"090E04FF": "Trace warning plc.cmp.motion"},
            {"090E0500": "Warning: Axis limits exceeded"},
            {"090E0FFD": "Trace warning motion.script"},
            {"090E0FFE": "Trace warning motion.collisionavoidance"},
            {"090E0FFF": "Trace warning motion.core"},
            {"090F0000": "General AxisProfile error"},
            {"090F0001": "AxisProfile configuration error"},
            {"090F0002": "AxisProfile profile error"},
            {"090F0003": "AxisProfile Data Layer provider error"},
            {"090F0004": "Switching the operation mode failed"},
            {"090F0005": "AxisProfile error on connected device"},
            {"090F0006": "Error in axis profile of the touch probe"},
            {"090F0007": "Error when scaling AxisProfile"},
            {"090F0050": "License for current configuration missing"},
            {"090F0051": "Axis configuration error"},
            {"090F0052": "Kinematic configuration error"},
            {"090F0053": "Error in system configuration"},
            {"090F0054": "Error during backup or restoration"},
            {"090F02FF": "Trace error common.axisprofile"},
            {"090F0400": "Error in plc data"},
            {"090F04FF": "Trace error plc.cmp.motion"},
            {"090F0500": "Error when loading the calculation pipeline"},
            {"090F0501": "Error when configuring the calculation pipeline"},
            {"090F0502": "Non-fatal error when validating the calculation pipeline"},
            {"090F0503": "Non-fatal error in axis command 'GearInPos'"},
            {"090F0504": "Non-fatal error in calculation pipeline"},
            {"090F0505": "Error when calling calculation step by the Data Layer"},
            {"090F0506": "Error when calling calculation step param by the Data Layer"},
            {"090F0507": "MAIN_DIAG_MOTION_CORE_GEARINVEL_CMD_ERROR_F0"},
            {"090F0FFD": "Trace error motion.script"},
            {"090F0FFE": "Trace error motion.collisionavoidance"},
            {"090F0FFF": "Trace error motion.core"},
            {"090F2000": "Device error"},
            {"090F2001": "General command error"},
            {"090F2002": "General axis command error"},
            {"090F2003": "Error in axis command 'AddToKin'"},
            {"090F2004": "Error in axis command 'RemoveFromKin'"},
            {"090F2005": "Error in axis command 'AddToMaster'"},
            {"090F2006": "Axis limit exceeded"},
            {"090F2007": "Error in axis jog command"},
            {"090F2008": "Error in axis Gantry command"},
            {"090F2009": "Error in axis command 'AddToGantry'"},
            {"090F200A": "Error in axis command 'RemoveFromGantry'"},
            {"090F200B": "Axis configuration error"},
            {"090F200C": "General axis command error"},
            {"090F200D": "Error in abort command of the axis"},
            {"090F200e Error in axis reset command"},
            {"090F200f Error in axis command MoveVelocity"},
            {"090F2010": "Kinematic configuration error"},
            {"090F2011": "General kinematic command error"},
            {"090F2012": "Kinematic limit exceeded"},
            {"090F2013": "Error in kinematic jog command"},
            {"090F2014": "Error in kinematic raw ipo command"},
            {"090F2015": "Error in additional command channel"},
            {"090F2016": "General command error"},
            {"090F2017": "Override error"},
            {"090F2018": "Error in kinematic command 'Group'"},
            {"090F2019": "Error in kinematic command 'Move'"},
            {"090F201A": "Error in kinematic command 'Contour'"},
            {"090F201B": "Error in the geometry object of the kinematics"},
            {"090F201C": "Error in the kinematic command 'PreWait'"},
            {"090F2020": "Error in system configuration"},
            {"090F2021": "Error during backup or restoration"},
            {"090F2030": "Error in command options"},
            {"090F2031": "Error in command option 'Blending'"},
            {"090F2032": "Error in command option product coordinate system"},
            {"090F2033": "Error in command option of machine coordinate system"},
            {"090F2034": "Error in cmd opt 'SafeZones' (safe zones and working areas)"},
            {"090F2035": "Error in command option 'PolyTrans'"},
            {"090F2040": "System error"},
            {"090F2050": "Error while running script"},
            {"090F2051": "Error in task/request comm. between script manager/instance"},
            {"090F2052": "Error in the system configuration"},
            {"090F2060": "Error in axis command 'EStop'"},
            {"090F2061": "Error in axis command 'PosAbs / PosRel / PosAdd'"},
            {"090F2062": "Error in axis command 'Power'"},
            {"090F2063": "Error in axis command 'Homing'"},
            {"090F2064": "Error regarding to the touch probe command of the Motion"},
            {"090F2500": "Error in axis command 'GearInPos'"},
            {"090F2501": "Error in axis command 'SyncPosGeneric'"},
            {"090F2502": "Error in the synchronized Motion command"},
            {"090F2503": "Error in the axis command 'gearInVel'"},
            {"090F2504": "Error in the axis command 'SyncVelGeneric'"},
            {"090F6000": "Error in the Sequence Manager"},
            {"090F6001": "Forced stop of the ctrlX Motion"},
            {"090F6010": "PLC detected error event"},
            {"090F8011": "General error in CXA_Motion"},
        ]
    }
